// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Environment variable validation with detailed error reporting
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// Log environment variable status for debugging (simplified to avoid React issues)
try {
  console.log('🔧 Supabase Environment Variables:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    urlPreview: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 30)}...` : 'MISSING'
  });

  // Validate required environment variables
  if (!SUPABASE_URL) {
    const error = new Error('❌ VITE_SUPABASE_URL environment variable is missing.');
    console.error(error.message);
    throw error;
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    const error = new Error('❌ VITE_SUPABASE_ANON_KEY environment variable is missing.');
    console.error(error.message);
    throw error;
  }
} catch (envError) {
  console.error('Environment variable validation failed:', envError);
  throw envError;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});